plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lingxi.music'
    compileSdk 34

    defaultConfig {
        applicationId "com.lingxi.music"
        minSdk 21
        targetSdk 34
        versionCode 35
        versionName "2.0.4"
    }

    signingConfigs {
        release {
            storeFile file("signing.keystore")
            storePassword "UhaUkWaHoZjf"
            keyAlias "my-key-alias"
            keyPassword "UhaUkWaHoZjf"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
}
